[package]
name = "SystemDash"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sysinfo = { version = "0.34.2", features = ["serde"] }
tokio = { version = "1.44.1", features = ["full"] }
warp = "0.3.7"
