name: Apple SystemDash Release

on:
  push:
    tags:
      - "v*"  # Runs only when pushing a version tag (e.g., v1.0.0)

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin,aarch64-apple-darwin

      - name: Install Rust target
        run: rustup target add x86_64-apple-darwin aarch64-apple-darwin

      - name: Clean cargo build cache
        run: cargo clean

      - name: Build project for macOS Intel (x86_64)
        run: cargo build --release --target x86_64-apple-darwin --verbose

      - name: Build project for macOS Apple Silicon (aarch64)
        run: cargo build --release --target aarch64-apple-darwin --verbose

      - name: Debug target output for macOS Intel
        run: ls -R target/x86_64-apple-darwin/release

      - name: Debug target output for macOS Apple Silicon
        run: ls -R target/aarch64-apple-darwin/release

      - name: Prepare artifacts
        run: |
          mkdir -p release
          cp target/x86_64-apple-darwin/release/SystemDash release/
          cp target/aarch64-apple-darwin/release/SystemDash release/
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SystemDash
          path: release/SystemDash

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts
        run: ls -R artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/* 
          token: ${{ secrets.GITHUB_TOKEN }}